INSERT INTO main_app_car(name, price, img, description, created_at)
  VALUES
    ('1961 Ferrari 250 GT California SWB Spider','$17 million', 'https://www.motortrend.com/uploads/sites/11/2015/05/1961-Ferrari-250-GT-SWB-front-three-quarters.jpg?fit=around%7C1000:625','If this car looks familiar, it might be because it’s similar to the one featured in the 1980s hit movie, “Ferris Bueller’s Day Off, reports CNBC. And it’s a gem, as evidenced by the sale of one in 2016 at an auction for $17.16 million. Only about 55 of these were ever made, making this particular model one of the most sought-after Ferraris on the market.','2021-05-07 18:57:42.517205-07');
INSERT INTO main_app_car(name, price, img, description, created_at)
  VALUES
    ('2009 Koenigsegg CCXR Trevita','$4.8 million', 'https://www.supercars.net/blog/wp-content/uploads/2016/01/2010-koenigsegg-ccxr-trevita-3.jpg','Just when you thought the CCXR couldn’t get any cooler, along comes the limited-edition Trevita. The CCXR Trevita uses white carbon fibers designed to shine like a million diamonds when light hits the car. The fiber was made specifically for this car, of which only two were built in 2009, according to Koenigsegg.This car is so hot that even Floyd Mayweather had to have one.','2021-05-07 18:57:42.517205-07');
INSERT INTO main_app_car(name, price, img, description, created_at)
  VALUES
    ('2013 Lamborghini Veneno','$11.1 million', 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/news/2019/08_08_veneno/COVER_VENENO.jpg','According to the Lamborghini website, the Veneno has a carbon-fiber, lightweight design and is consistently focused on optimum aerodynamics and cornering stability. When the car made an appearance at the Geneva Motor Show in 2013, multiple sites noted that the Veneno has 750 horsepower and a top speed of 220 mph.','2021-05-07 18:57:42.517205-07');
INSERT INTO main_app_car(name, price, img, description, created_at)
  VALUES
    ('W Motors Lykan Hypersport','$3.4 million', 'https://www.wallpaperup.com/uploads/wallpapers/2015/02/26/629640/99d4660281b8e9dab76e2eadef6c841d-1000.jpg','If you’ve seen “Furious 7,” you might recall watching this car smash through skyscrapers, reports Road & Track. Deemed the “first Arab supercar” by W Motors, the Lykan Hypersport costs $3.4 million, reports CNN. It can go from 0 to 62 mph in 2.8 seconds and has a top speed of 240 mph. Your $3.4 million will also buy you a leather interior stitched with gold thread, a 3D infotainment system that can generate [holographs] and LED headlamps encrusted with diamonds.','2021-05-07 18:57:42.517205-07');
INSERT INTO main_app_car(name, price, img, description, created_at)
  VALUES
    ('2017 Pagani Huayra BC','$2.75 - 3.25 million', 'https://wallpaperaccess.com/full/2305220.jpg','This auto is an engineering tour de force. And only 20 units were made, according to AutoGuide.com. The carbon fiber used on the bodywork is a unique formula that’s 50 percent lighter than regular carbon fiber. And, it can hit 0 to [approximately] 60 mph in 2.8 seconds.','2021-05-07 18:57:42.517205-07');
INSERT INTO main_app_car(name, price, img, description, created_at)
  VALUES
    ('1954 Oldsmobile F-88','$3.24 million', 'https://c4.wallpaperflare.com/wallpaper/482/68/984/oldsmobile-f-88-concept-wallpaper-preview.jpg','Let’s just say that this is not your father’s Oldsmobile — unless he’s a serious collector. Those looking for rare cars for sale should definitely check out the Oldsmobile F-88. The 1954 Oldsmobile F-88 concept car fetched $3.24 million at auction in 2005. According to a 2005 CNN Money article, this gem has a 324-cubic-inch Oldsmobile Rocket V-8 engine and gets up to 250 horsepower.','2021-05-07 18:57:42.517205-07');
INSERT INTO main_app_car(name, price, img, description, created_at)
  VALUES
    ('1931 Bugatti Type 41 Royale Kellner Coupe','$9.8 million', 'https://investinangra.com/images/2019/SETEMBRO/M/243.jpg','Only three of the six Bugatti Type 41 Royales ever produced were sold, reports CarBuzz. However, because the unbodied chassis cost $30,000 when it was first made during the Great Depression, it’s no surprise that sales were low. In 1987, AP reported that one sold for $9.8 million, which at the time was the highest price ever paid for a car.','2021-05-07 18:57:42.517205-07');
INSERT INTO main_app_car(name, price, img, description, created_at)
  VALUES
    ('1964 Ford GT40','$7 million', 'https://wallpaperaccess.com/full/2768899.jpg','An American classic, the prototype for the 1964 Ford GT40 sold for $7 million in 2014, reported Motor1.','2021-05-07 18:57:42.517205-07');
INSERT INTO main_app_car(name, price, img, description, created_at)
  VALUES
    ('1957 Ferrari 250 Testa Rossa','$39.8 million', 'https://w0.peakpx.com/wallpaper/177/536/HD-wallpaper-ferrari-250-testa-rossa-ferrari-tr-24-hours-of-le-mans-retro-racing-car-classic-sports-cars-ferrari.jpg','The 1957 Ferrari 250 Testa Rossa is one of just 34 models ever built, said Shibarshin. Along with racing around the world and gathering numerous wins, the car was known for its impeccable styling. Today, the Testa Rossa is worth tens of millions. In fact, an unrestored 250 Testa Rossa traded hands in 2014 for nearly $40 million, according to AutoBlog.','2021-05-07 18:57:42.517205-07');